image: gumjoe/wacc-ci-scala:slim

stages:
  - build
  - test_valid
  - test_invalid_syntax
  - test_invalid_semantics

build:
  stage: build
  script:
    - scala compile .

test_valid:
  stage: test_valid
  script:
    - echo "Testing WACC programs that are valid..."
    - scala-cli test test/wacc/valid
  # when: never

test_invalid_syntax:
  stage: test_invalid_syntax
  script:
    - echo "Testing WACC programs with invalid syntax..."
    - scala-cli test test/wacc/invalid_syntax
  # when: never

test_invalid_semantics:
  stage: test_invalid_semantics
  script:
    - echo "Testing WACC programs with invalid semantics..."
    - scala-cli test test/wacc/invalid_semantics
  # when: never