image: gumjoe/wacc-ci-scala:slim

stages:
  - build
  - test

build:
  stage: build
  script:
    - scala compile .

test:
  stage: test
  script:
    - echo "Testing WACC programs..."
    - scala-cli test .
  # when: never